name: com_rawand_ayatulkursi
description: This app is created for those who want to read and listen to Ayat Al-Kursi daily.
publish_to: "none"

version: 1.4.0+5

environment:
  sdk: ">=3.1.0-83.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: any
  audioplayers: any
  url_launcher: ^6.1.11
  dynamic_color: ^1.6.5
  shared_preferences: ^2.1.2
  flutter_local_notifications: ^14.1.1

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/audio/ayatul-kursi.mp3
    - assets/rawand.png
    - assets/logo.png

  fonts:
    - family: Quran
      fonts:
        - asset: assets/fonts/quran.ttf
    - family: Google
      fonts:
        - asset: assets/fonts/regular.ttf
        - asset: assets/fonts/italic.ttf
          style: italic
        - asset: assets/fonts/bold.ttf
          weight: 700
    - family: Sahel
      fonts:
        - asset: assets/fonts/sahel.ttf
        - asset: assets/fonts/sahel-bold.ttf
          weight: 700
